#!/bin/sh
set -e

# Stop and disable the systemd service
if [ -x "$(command -v systemctl)" ]; then
    systemctl stop gisnav-compose.service
    systemctl disable gisnav-compose.service
fi

# Execute docker-compose down
# "down" removes containers, volumes, networks
if [ -x "$(command -v docker)" ]; then
    cd /etc/gisnav-compose
    docker compose -p gisnav down
fi

# Remove the systemd service file
case "$1" in
    purge|remove)
        # Remove systemd service file
        if [ -f /etc/systemd/system/gisnav-compose.service ]; then
            rm -f /etc/systemd/system/gisnav-compose.service
            systemctl daemon-reload
        fi
        # Remove the compose files directory
        if [ -d /etc/gisnav-compose ]; then
            rm -rf /etc/gisnav-compose
        fi
        ;;
esac

exit 0
