gscam_publisher:
  ros__parameters:
    gscam_config: >
      udpsrc port=5600 caps="application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264"
      ! tee name=t
      ! queue
      ! udpsink host=0.0.0.0 port=5601
      t.
      ! queue
      ! rtph264depay
      ! avdec_h264
      ! videorate
      ! video/x-raw,framerate=5/1
      ! videoconvert
      ! video/x-raw,format=GRAY8
    preroll: False
    use_gst_timestamps: False  # use ROS time, important
    frame_id: 'mono'
    image_encoding: 'mono8'
