FROM ghcr.io/gethomepage/homepage:latest

LABEL maintainer="Harri Makelin <hmakelin@protonmail.com>"

COPY config/ /app/config/
COPY logo-no-background.svg gisnav-website-favicon-color.png /app/public/images/
