ARG BASE_IMAGE=nvcr.io/nvidia/l4t-pytorch:r32.6.1-pth1.9-py3
FROM ${BASE_IMAGE}

LABEL maintainer="Harri Makelin <hmakelin@protonmail.com>"

# Newest version of torch serve will not install for the Python 3.6 included in base image
ARG TORCHSERVE_VERSION=v0.4.2
ARG CUDA=102
ENV CUDA=${CUDA}

RUN apt update && \
    apt install sudo

RUN git clone https://github.com/pytorch/serve.git && \
    cd serve && \
    git checkout tags/${TORCHSERVE_VERSION} && \
    alias python=python3 && \
    alias pip=pip3 && \
    ln -s /usr/bin/pip3 /usr/bin/pip

RUN useradd -m model-server && \
    mkdir -p /home/model-server

USER model-server

COPY --chmod=755 create_pth.py setup.sh /home/model-server/
COPY loftr_handler.py ts_config /home/model-server/

# TODO: need to have proper solution for this part
ENTRYPOINT python3 ./serve/ts_scripts/install_dependencies.py --cuda=cu${CUDA} && \
    pip install torchserve torch-model-archiver torch-workflow-archiver && \
    $HOME/setup.sh

CMD ["torchserve", \
    "--start", \
    "--ncs", \
    "--model-store", "model_store", \
    "--models", "loftr=loftr.mar", \
    "--ts-config", "$HOME/ts_config"]